version: '3.9'

services:
  node:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: "node:20"
    user: "node"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 3G
    networks:
      - app-network

  db:
    image: mysql:5.7
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    container_name: db
    volumes:
      - my-db:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - '3306:3306'
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 3G

networks:
  app-network:
    driver: bridge
volumes:
  my-db:
  node_modules:  
